from __future__ import annotations
import ast, hashlib, json
from pathlib import Path
from src.context import liquidity_sweep_pattern_context_v1 as m

CAPABILITY="LIQUIDITY_SWEEP_PATTERN_CONTEXT_V1_VALIDATOR"
POLICY=Path("src/context/resources/liquidity_sweep_pattern_context_policy_v1.json"); SOURCE=Path("src/context/liquidity_sweep_pattern_context_v1.py"); DOCS=Path("docs/LIQUIDITY_SWEEP_PATTERN_CONTEXT_V1.md"); TESTS=Path("tests/test_liquidity_sweep_pattern_context_v1.py"); MANIFEST=Path("LIQUIDITY_SWEEP_PATTERN_CONTEXT_V1_MANIFEST.sha256")
def sha(path):
    h=hashlib.sha256(); h.update(path.read_bytes()); return h.hexdigest()
def run():
    source=SOURCE.read_text(); docs=DOCS.read_text(); tests=TESTS.read_text(); policy=json.loads(POLICY.read_text()); tree=ast.parse(source); imports=sorted({n.names[0].name.split('.')[0] for n in ast.walk(tree) if isinstance(n,ast.Import)}|{(n.module or '').split('.')[0] for n in ast.walk(tree) if isinstance(n,ast.ImportFrom) and n.module}); checks=[]
    def check(name,ok,details): checks.append({"check":name,"passed":bool(ok),"details":details,"blocker":not bool(ok)})
    check("capability",m.CAPABILITY=="LIQUIDITY_SWEEP_PATTERN_CONTEXT_V1",m.CAPABILITY); check("feature",m.FEATURE_ID==m.CAPABILITY,m.FEATURE_ID); check("source_kind",m.SOURCE_KIND=="OBSERVED_MARKET",m.SOURCE_KIND); check("attempt",m.IMPLEMENTATION_OR_REPAIR_ATTEMPT==1,str(m.IMPLEMENTATION_OR_REPAIR_ATTEMPT)); check("max_attempts",m.MAX_IMPLEMENTATION_OR_REPAIR_ATTEMPTS==10,str(m.MAX_IMPLEMENTATION_OR_REPAIR_ATTEMPTS)); check("auth",m.PACKAGE_AUTHORIZATION=="PREPARE_LIQUIDITY_SWEEP_PATTERN_CONTEXT_V1",m.PACKAGE_AUTHORIZATION); check("lookback",m.ROLLING_EXTREME_LOOKBACK_BARS==48,str(m.ROLLING_EXTREME_LOOKBACK_BARS)); check("atr",m.ATR_BARS==14,str(m.ATR_BARS))
    check("policy_schema",policy["schema_version"]=="LIQUIDITY_SWEEP_PATTERN_CONTEXT_POLICY_V1",policy["schema_version"]); check("policy_floor",policy["policy_effective_from_utc"]=="2026-08-17T00:00:00+00:00",policy["policy_effective_from_utc"]); check("policy_source",policy["source_capture_capability"]=="LONG_PRIMARY_PUBLIC_CLOSED_CANDLE_CAPTURE_V1",policy["source_capture_capability"]); check("policy_provider",policy["source_provider"]=="BINANCE_PUBLIC_SPOT_API",policy["source_provider"]); check("policy_same_bar",policy["same_bar_response_only"] is True,"true"); check("policy_no_future",policy["future_bar_confirmation_used"] is False,"false"); check("policy_symmetric",policy["symmetric_high_low_context"] is True,"true"); check("policy_proxy",policy["sweep_is_price_action_proxy_only"] is True,"true"); check("policy_no_hidden_stops",policy["hidden_stop_orders_observed"] is False,"false"); check("policy_no_liq",policy["liquidations_observed"] is False,"false"); check("policy_no_primary",policy["primary_candidate_semantics_reused"] is False,"false"); check("policy_no_direction",policy["directional_meaning_assigned"] is False,"false"); check("policy_no_score",policy["composite_score_assigned"] is False,"false"); check("policy_no_signal",policy["signal_semantics"] is False,"false")
    check("pack_dependency","context_feature_pack_v1_level_a_standard" in source,"present"); check("capture_validator","validate_closed_candle_capture" in source,"present"); check("no_capture_call","capture_real_binance_public_closed_candles" not in source,"absent"); check("no_requests","requests" not in imports,json.dumps(imports)); check("no_httpx","httpx" not in imports,json.dumps(imports)); check("no_websocket","websocket" not in imports and "websockets" not in imports,json.dumps(imports)); check("no_threads",not any(x in imports for x in ("threading","multiprocessing","asyncio","schedule","apscheduler")),json.dumps(imports)); check("no_subprocess","subprocess" not in imports,json.dumps(imports)); check("no_official_writer","append_official_prospective_evidence" not in source,"absent")
    check("reference_boundary","REFERENCE_BOUNDARY_INVALID" in source,"present"); check("source_match","SOURCE_REFERENCE_CANDLE_MISMATCH" in source,"present"); check("capture_after_reference","SOURCE_CAPTURE_BEFORE_REFERENCE" in source,"present"); check("policy_floor_applied","available=max(captured,policy_effective)" in source,"present"); check("info_cutoff",'"information_cutoff_utc":_utc(reference)' in source,"present"); check("rolling_low","lo=min(float(c[\"low\"]) for c in preceding)" in source,"present"); check("rolling_high","hi=max(float(c[\"high\"]) for c in preceding)" in source,"present"); check("latest_excluded","candles[-49:-1]" in source,"present"); check("lower_strict","lower=l<lo" in source,"present"); check("lower_reclaim","lower_reclaim=c>lo" in source,"present"); check("upper_strict","upper=h>hi" in source,"present"); check("upper_reject","upper_reject=c<hi" in source,"present"); check("two_sided","two_sided_sweep_same_bar" in source,"present"); check("atr_metric","lower_excursion_atr" in source and "upper_excursion_atr" in source,"present"); check("wick_metric","upper_wick_fraction_of_range" in source and "lower_wick_fraction_of_range" in source,"present"); check("volume_metric","statistics.median" in source,"present")
    check("no_hidden_claim",'"hidden_stop_orders_observed":False' in source,"present"); check("no_liq_claim",'"liquidations_observed":False' in source,"present"); check("no_primary_semantics",'"primary_candidate_semantics_reused":False' in source,"present"); check("no_secondary_promotion",'"secondary_candidate_promoted":False' in source,"present"); check("no_candidate",'"candidate_emitted":False' in source,"present"); check("no_outcomes",'"future_outcomes_used":False' in source,"present"); check("no_direction",'"directional_semantics":False' in source,"present"); check("no_signal",'"signal_semantics":False' in source,"present"); check("no_score",'"composite_score_assigned":False' in source,"present"); check("no_market_acq",'"market_data_acquired_by_producer":False' in source,"present"); check("no_recapture",'"source_recaptured_by_producer":False' in source,"present")
    check("external_source","closed_candle_capture_directory" in source,"present"); check("source_outside_repo","SOURCE_CAPTURE_INSIDE_REPOSITORY_PROHIBITED" in source,"present"); check("external_output","OUTPUT_INSIDE_REPOSITORY_PROHIBITED" in source,"present"); check("create_only",'with path.open("xb")' in source,"present"); check("official_integrity","OFFICIAL_ARTIFACT_CHANGED" in source,"present")
    check("docs_proxy","price-action proxy" in docs,"present"); check("docs_floor","Policy floor" in docs,"present"); check("docs_primary","LONG_BASE_FAILED_BREAKDOWN_V1" in docs,"present"); check("docs_secondary","LONG_BASE_LIQUIDITY_SWEEP_V1" in docs,"present"); check("docs_no_edge","not evidence of an edge" in docs,"present"); check("test_lower","test_05_lower_sweep_reclaim" in tests,"present"); check("test_upper","test_07_upper_sweep_rejection" in tests,"present"); check("test_two_sided","test_09_two_sided" in tests,"present"); check("test_floor","test_19_old_floor" in tests,"present"); check("test_roundtrip","test_24_roundtrip" in tests,"present"); check("test_tamper","test_25_tamper" in tests,"present"); check("test_official","test_26_official_unchanged" in tests,"present"); check("test_source_unchanged","test_27_source_unchanged" in tests,"present")
    try:
        pv=m.validate_liquidity_sweep_pattern_context_policy_v1(policy); ok=pv["rolling_extreme_lookback_bars"]==48 and pv["atr_bars"]==14; details=json.dumps(pv,sort_keys=True)
    except Exception as exc: ok=False; details=repr(exc)
    check("runtime_policy",ok,details)
    lines=[x for x in MANIFEST.read_text().splitlines() if x.strip()]; manifest_ok=len(lines)==5
    if manifest_ok:
        for line in lines:
            parts=line.split("  ",1)
            if len(parts)!=2 or len(parts[0])!=64 or not Path(parts[1]).is_file() or sha(Path(parts[1]))!=parts[0]: manifest_ok=False; break
    check("manifest_entries",len(lines)==5,str(len(lines))); check("manifest_valid",manifest_ok,str(manifest_ok))
    failed=[x for x in checks if not x["passed"]]; blockers=[x for x in checks if x["blocker"]]
    return {"capability":CAPABILITY,"checks":len(checks),"failed_checks":len(failed),"blockers":len(blockers),"check_results":checks,"decision":"LIQUIDITY_SWEEP_PATTERN_CONTEXT_V1_VALIDATED_NO_REAL_NETWORK" if not blockers else "BLOCKED","real_network_request_executed":False,"real_market_data_acquired":False,"real_component_package_prepared":False,"official_append_executed":False}
if __name__=="__main__":
    r=run(); print(json.dumps(r,indent=2,sort_keys=True)); raise SystemExit(0 if r["blockers"]==0 else 1)
